---
abstract: 'A Perl module for protein contact interfaces evolutive analysis'
author:
  - 'Hector Valverde <hvalverde@uma.es>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mecom
no_index:
  directory:
    - t
    - inc
requires:
  Bio::Align::IO: 0
  Bio::Align::Utilities: 0
  Bio::SeqIO: 0
  Bio::SimpleAlign: 0
  Bio::Structure::IO::pdb: 0
  Bio::Structure::Model: 0
  Bio::Structure::SetcStr::DSSP::Res: 0
  Bio::Tools::Run::Phylo::PAML::Yn00: 0
  Carp: 0
  Getopt::Long: 0
  IPC::Run: 0
  Number::Formating: 0
  Statistics::Basic: 0
  Statistics::Zed: 0
  perl: 5.006
version: 1.08
